const types = {
  POSSIBLE_MATCHING: 'POSSIBLE_MATCHING',
  DOBLE_CONFIRMATION: 'DOBLE_CONFIRMATION',
  NEW_PUBLICATION: 'NEW_PUBLICATION',
  DELETED_FOR_COMPLAINTS: 'DELETED_FOR_COMPLAINTS'
};

export default {
  types
};
