const types = {
  POSSIBLE_MATCHING: 'POSSIBLE_MATCHING',
  DOBLE_CONFIRMATION: 'DOBLE_CONFIRMATION',
  DELETED_FOR_COMPLAINTS: 'DELETED_FOR_COMPLAINTS',
  TEMPORAL_PUBLICATION: 'TEMPORAL_PUBLICATION'
};

export default {
  types
};
