export const CLEAR_STORE = 'PUBLICATION/CLEAR_STORE';

export const CREATE_PUBLICATION_FAILURE = 'PUBLICATION/CREATE_FAILURE';
export const CREATE_PUBLICATION_REQUEST = 'PUBLICATION/CREATE_REQUEST';
export const CREATE_PUBLICATION_SUCCESS = 'PUBLICATION/CREATE_SUCCESS';

export const GET_EXTRACTED_COLORS = 'PUBLICATION/GET_EXTRACTED_COLORS';

export const SET_ADDITIONAL_INFORMATION =
  'PUBLICATION/SET_ADDITIONAL_INFORMATION';
export const SET_EXTRACTED_COLORS = 'PUBLICATION/SET_EXTRACTED_COLORS';
export const SET_EXTRACTING_COLORS = 'PUBLICATION/SET_EXTRACTING_COLORS';
export const SET_HAS_CHANGES = 'PUBLICATION/SET_HAS_CHANGES';
export const SET_LOCATION_ID = 'PUBLICATION/SET_LOCATION_ID';
export const SET_PET_COLLAR = 'PUBLICATION/SET_PET_COLLAR';
export const SET_PET_COLOR = 'PUBLICATION/SET_PET_COLOR';
export const SET_PET_GENDER = 'PUBLICATION/SET_PET_GENDER';
export const SET_PET_TYPE = 'PUBLICATION/SET_PET_TYPE';
export const SET_PET_SIZE = 'PUBLICATION/SET_PET_SIZE';
export const SET_PHOTOS_ARRAY = 'PUBLICATION/SET_PHOTOS_ARRAY';
export const SET_PHONE_NUMBER = 'PUBLICATION/SET_PHONE_NUMBER';
export const SET_PUBLICATION_REWARD = 'PUBLICATIO/SET_PUBLICATION_REWARD';
export const SET_PUBLICATION_TYPE = 'PUBLICATION/SET_PUBLICATION_TYPE';
export const SET_USER_ID = 'PUBLICATION/SET_USER_ID';
