export const SET_HAS_REFRESH_HOME = 'REFRESHMENTS/SET_HAS_REFRESH_HOME';
export const SET_HAS_REFRESH_PROFILE = 'REFRESHMENTS/SET_HAS_REFRESH_PROFILE';
export const SET_HAS_REFRESH_FAVORITES = 'SET_HAS_REFRESH_FAVORITES';
